### ISSUE TITLE
Schematic / PCB Review

### ISSUE THREAD

**Issue by mlp6** [haerynkim/FlashlightRepos#5]
Looking good... not sure about functionality, but board layout is getting there.  What was the difference b/w v1 and v2?

**Comment by sphaerobolus** [comment]
Schematic looks pretty good. 

increase trace width. 20mil where you can, otherwise 12mil. 

looks like a trace going to R3 doesn't quite make it all the way. 

The crystal footprint isn't quite right. The crystal we use has pins 0.2" (200mil) apart.

150 Ohm pull up resistor is too small. 10k, maybe.
